import '@app/ui/styles.css';
import styles from '../fonts';
import type { Metadata } from 'next';
import { NextProvider } from '@app/ui';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={styles}>
        <NextProvider>{children}</NextProvider>
      </body>
    </html>
  );
}
